---
- name: Provision EC2 instance
  become: false
  connection: local
  hosts: localhost

  tasks:
  - name: install boto
    pip:
      name: boto
 
 #Please change instance_type and image ID if needed
 #Current version is for JBoss EAP Demo#
  - name: Create AWS Instance
    ec2:
      key_name: dleong
      instance_type: t2.small
      image: ami-07cafca3788493264
      wait: yes
      count: 1
      vpc_subnet_id: subnet-031c204a
      group: insecure_all
      region: ap-southeast-1
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"

